# Generated by Django 5.2.15 on 2026-07-07 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readbooks',
            name='review',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
